### PR TITLE
initial push for processed data

### PR DESCRIPTION
**Pull request by DriftingShadows**
Let me know if you require any changes.

### CODE REVIEW

**Comment by thariyarox** [comment]
@DriftingShadows - Good job ! I tested the program and it works as expected. I would like to suggest few improvements.

1. Create a folder named 'processors' in the main project folder and put the python program into that folder. 
2. When you are generating the CSV file, that should be generated inside the 'data' folder.

**Comment by DriftingShadows** [comment]
Thanks for the suggestion! I realise the csv file path is not particularly dynamic is fixed at the moment to point to the test_data.csv . Not sure if that needs to be changed.

**Review by thariyarox — APPROVED** [review]
Reviewed the fix and approved

**Comment by thariyarox** [comment]
@DriftingShadows  - Thanks a lot for the contribution !!!

**Pull request merged**
