### PR TITLE
added the pipeline for adding data to the text file 

### PR DESCRIPTION
**Pull request by codescientist703**

### CODE REVIEW

**Comment by djeni98** [comment]
@codescientist703 I think it will be good to add `return item` at the end of the method `process_item`. In this way, running `scrapy crawl coinspot -o test_data.csv` will still work.

**Comment by thariyarox** [comment]
@djeni98 Yes, I tested your suggestion to add the return item and it works. Thanks !

@codescientist703 - Can you please add the 'return item' line in the process_item method and also modify the readme file to include instructions for running the crawler in both modes (one without generating the CSV file and the other to generate the CSV file with -o parameter.

**Comment by codescientist703** [comment]
@thariyarox  I have done the changes as you requested.

**Comment by thariyarox** [comment]
@codescientist703  Thanks, I've merged the PR !

**Pull request merged**
